import { defineConfig } from "tsup";

export default defineConfig((options) => ({
  entryPoints: [
    "src/accordion.tsx",
    "src/avatar.tsx",
    "src/badge.tsx",
    "src/breadcrumb.tsx",
    "src/button.tsx",
    "src/button-group.tsx",
    "src/calendar.tsx",
    "src/carousel.tsx",
    "src/alert.tsx",
    "src/alert-dialog.tsx",
    "src/aspect-ratio.tsx",
    "src/card.tsx",
    "src/checkbox.tsx",
    "src/collapsible.tsx",
    "src/combobox.tsx",
    "src/date-input.tsx",
    "src/description-list.tsx",
    "src/drawer.tsx",
    "src/empty.tsx",
    "src/dropdown-menu.tsx",
    "src/field.tsx",
    "src/form.tsx",
    "src/item.tsx",
    "src/input.tsx",
    "src/input-group.tsx",
    "src/input-otp.tsx",
    "src/kbd.tsx",
    "src/label.tsx",
    "src/modal.tsx",
    "src/native-select.tsx",
    "src/pagination.tsx",
    "src/popover.tsx",
    "src/progress.tsx",
    "src/radio-group.tsx",
    "src/select.tsx",
    "src/separator.tsx",
    "src/skeleton.tsx",
    "src/slider.tsx",
    "src/spinner.tsx",
    "src/stepper.tsx",
    "src/switch.tsx",
    "src/table.tsx",
    "src/tabs.tsx",
    "src/textarea.tsx",
    "src/tag.tsx",
    "src/tag-group.tsx",
    "src/toast.tsx",
    "src/toggle.tsx",
    "src/toggle-group.tsx",
    "src/tooltip.tsx",
    "src/utils.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  external: ["react"],
  ...options,
}));
