import { defineConfig } from "tsup";

export default defineConfig((options) => ({
  entryPoints: [
    "src/accordion.tsx",
    "src/avatar.tsx",
    "src/badge.tsx",
    "src/button.tsx",
    "src/button-group.tsx",
    "src/calendar.tsx",
    "src/card.tsx",
    "src/checkbox.tsx",
    "src/combobox.tsx",
    "src/date-input.tsx",
    "src/dropdown-menu.tsx",
    "src/field.tsx",
    "src/form.tsx",
    "src/input.tsx",
    "src/input-group.tsx",
    "src/input-otp.tsx",
    "src/kbd.tsx",
    "src/label.tsx",
    "src/native-select.tsx",
    "src/popover.tsx",
    "src/radio-group.tsx",
    "src/select.tsx",
    "src/separator.tsx",
    "src/switch.tsx",
    "src/tabs.tsx",
    "src/textarea.tsx",
    "src/utils.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  external: ["react"],
  ...options,
}));
